server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///users/Carlos/Documents/workspace-sts-4-4.1.1/configuraciones